export const LIST_SEARCH_RESULTS = 'LIST_SEARCH_RESULTS';
export const ADD_ITEM = 'ADD_ITEM';
export const SWITCH_ADD_ITEM_MODE = 'SWITCH_ADD_ITEM_MODE';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const SWITCH_PROGRESS_UPDATE = 'SWITCH_PROGRESS_UPDATE';
export const UPDATE_CHAPTER = 'UPDATE_CHAPTER';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const LIST_USERS = 'LIST_USERS';

export const SET_ERRORS = 'SET_ERRORS';
