export const LIST_SEARCH_RESULTS = 'LIST_SEARCH_RESULTS';
export const ADD_BOOK = 'ADD_BOOK';
export const SWITCH_ADD_BOOK_MODE = 'SWITCH_ADD_BOOK_MODE';
export const REMOVE_BOOK = 'REMOVE_BOOK';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const SWITCH_PROGRESS_UPDATE = 'SWITCH_PROGRESS_UPDATE';
export const UPDATE_CHAPTER = 'UPDATE_CHAPTER';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_ERRORS = 'SET_ERRORS';
